### ISSUE TITLE
InnerText?

### ISSUE THREAD

**Issue by marcelinhov2** [vrajroham/vue-circle-progress#10]
Hey guys, what happened to the innerText prop?

**Comment by marcelinhov2** [comment]
I'd found the slot option. Sorry!

**Comment by skinnyjames** [comment]
@marcelinhov2 - sounds good!
One difference to note, is that the circles show the inner-text and the progress percentage at the same time.  If you only want to show the inner-text, you'll want to set the show-percent prop to false. 

Hope this helps!

**Comment by amaralDaniel** [comment]
Hey, I've set the inner-text slot and although it shows on the inspector, it is not shown in the UI. Any thoughts?

**Comment by skinnyjames** [comment]
@amaralDaniel are you on the latest version?
You should be able to specify inner text by writing the markup inside the <vue-circle></vue-circle> tag.

**Comment by Pwntus** [comment]
Hey guys! This is somewhat relevant to the slot/inner text.
Correct me if I'm wrong, but there's no way to bind a value to the slot.
I want to show a (custom) value inside the ring, but I have no way of updating this value as new data becomes available.
