### ISSUE TITLE
Add repository field to package.json

### ISSUE THREAD

**Issue by ajmas** [vrajroham/vue-circle-progress#14]
When looking at the project there is no repository field, causing there to be no link-back to the GitHub project in the npm page:

https://www.npmjs.com/package/vue2-circle-progress

**Comment by skinnyjames** [comment]
I added and published, but I still don't see the link back :(

**Comment by ajmas** [comment]
There is a typo. Should be `repository`, instead of `repsitory`. :)

**Comment by skinnyjames** [comment]
Oh wow, it's been a long day.
this is fixed :)

**Comment by ajmas** [comment]
Looks good closing ticket.
