### ISSUE TITLE
"progress" doesn't v-bind properly

### ISSUE THREAD

**Issue by pengss** [vrajroham/vue-circle-progress#18]
Lets say I bind progress like this:

:progress = "changing_value"

The first time upon loading works perfectly, however, when the "changing_value" changes, :progress is not updated accordingly. Is there anything that I am doing wrong? Appreciate the help :)

**Comment by Daidalos117** [comment]
Did you solve it? I have same problem and just cant figure it out :/

**Comment by pengss** [comment]
Hey man,

I can't remember whether this resolved it exactly (it's been quite long ago). I went back to see my code, maybe you can try this out.

this.$refs.yourCircleName.updateProgress(percentage);

Just reference the targeted Vue Circle and use updateProgress().

**Comment by Daidalos117** [comment]
Thanks for reply! 
I made it the same way as you did. But it doesn't seem right (but maybe I am wrong?). If binded properly, it would be better no?

**Comment by pengss** [comment]
Maybe you can leave that piece of code here so that I can take a look for you :)

**Comment by zgmrvn** [comment]
the manual update of pengss works but we shoudn't have to do that
