### ISSUE TITLE
Method to update fill color

### ISSUE THREAD

**Issue by marcelinhov2** [vrajroham/vue-circle-progress#6]
Hey, how are you guys? What an awesome components...

I'm wondering if it's possible to update my ```fill``` color after render.

Thanks.

**Comment by vrajroham** [comment]
@marcelinhov2 Nice Input! 🎉  Will implement it soon and revert you here!

Thanks

**Comment by skinnyjames** [comment]
The jquery library describes it here: https://github.com/kottenator/jquery-circle-progress/issues/41

An example would be a method:
```
...
    changeColor: function(colorPayload){
      let circle = $(this.$el).data('circle-progress');
      circle.fill = colorPayload;
      circle.initFill();
    },
...
```
And then in the vue-circle-progress event in your App you could do something like: 
```
      .....
      progress(event,progress,stepValue){
        if (stepValue > 30) {
          this.$refs.myprogress.changeColor({color: '#e3f218'});
        }
      },
      .....
```
